site_name: voice2json
theme:
  name: material

nav:
  - Home: index.md
  - Installation Guide: install.md
  - Command Line Tools: commands.md
  - Template Language: sentences.md
  - Data Formats: formats.md
  - Profiles: profiles.md
  - Recipes: recipes.md
  - Whitepaper: whitepaper.md
  - About: about.md
markdown_extensions:
  - codehilite
